// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe-_WetGZp7VhW57LD2xPHMDjwq0IMX-E',
    appId: '1:259430226986:web:083164f42070233fc2b753',
    messagingSenderId: '259430226986',
    projectId: 'grab-umh-dcc8e',
    authDomain: 'grab-umh-dcc8e.firebaseapp.com',
    storageBucket: 'grab-umh-dcc8e.firebasestorage.app',
    measurementId: 'G-VL8R7R3LJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi7gYhBzirqgahDN6HniLlx8ykMZJdh4w',
    appId: '1:259430226986:android:a44ea2584e2c43d2c2b753',
    messagingSenderId: '259430226986',
    projectId: 'grab-umh-dcc8e',
    storageBucket: 'grab-umh-dcc8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDk3fyuALgJfp_GXwfWWjF3cyuJxIsPVg',
    appId: '1:259430226986:ios:04ca224e2457d1c3c2b753',
    messagingSenderId: '259430226986',
    projectId: 'grab-umh-dcc8e',
    storageBucket: 'grab-umh-dcc8e.firebasestorage.app',
    iosBundleId: 'com.example.grabUmh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDk3fyuALgJfp_GXwfWWjF3cyuJxIsPVg',
    appId: '1:259430226986:ios:04ca224e2457d1c3c2b753',
    messagingSenderId: '259430226986',
    projectId: 'grab-umh-dcc8e',
    storageBucket: 'grab-umh-dcc8e.firebasestorage.app',
    iosBundleId: 'com.example.grabUmh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe-_WetGZp7VhW57LD2xPHMDjwq0IMX-E',
    appId: '1:259430226986:web:bddff469cc44374ac2b753',
    messagingSenderId: '259430226986',
    projectId: 'grab-umh-dcc8e',
    authDomain: 'grab-umh-dcc8e.firebaseapp.com',
    storageBucket: 'grab-umh-dcc8e.firebasestorage.app',
    measurementId: 'G-JQNC975G6F',
  );
}
